### ISSUE TITLE
e3kit-node using this in electron v8.3.0

### ISSUE THREAD

**Issue by camhart** [VirgilSecurity/virgil-crypto-javascript#90]
I get the following error when attempting to use this package as part of e3kit-node in electron v8.3.0.

```
RuntimeError: abort(UnhandledRejection TypeError: `groupStorageName` is not a valid path). Build with -s ASSERTIONS=1 for more info.
    at process.B (webpack:///./node_modules/@virgilsecurity/core-foundation/node.es.js?:2:2534)
    at process.emit (events.js:215:7)
    at process.EventEmitter.emit (domain.js:476:20)
    at processEmit (webpack:///./node_modules/proper-lockfile/node_modules/signal-exit/index.js?:155:32)
    at processEmit [as emit] (C:\Users\Cam\projects\netcountable-desktop\truple\node_modules\write-file-atomic\node_modules\signal-exit\index.js:155:32)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
```

**Comment by camhart** [comment]
Digging into it, I believe this is actually an e3kit bug--yet it's actually an is-invalid-path bug.
